# Generated by Django 4.1.4 on 2022-12-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
