# Generated by Django 4.1.4 on 2022-12-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_user_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
