# Generated by Django 4.1.5 on 2023-04-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
    ]
