# Generated by Django 4.1.5 on 2023-04-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0007_remove_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
    ]
