# Generated by Django 4.1.5 on 2023-04-13 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_about_product_dimensions_product_weight'),
        ('comments', '0005_remove_comment_owner_remove_comment_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='productOwner',
        ),
        migrations.AddField(
            model_name='comment',
            name='productReviewed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product'),
            preserve_default=False,
        ),
    ]
