export const options = [
  { value: 'All', label: 'All' },
  { value: 'Baby', label: 'Baby' },
  { value: 'Beauty', label: 'Beauty' },
  { value: 'Books', label: 'Books' },
  { value: 'Fashion', label: 'Fashion' },
  { value: 'Car & Motorbike', label: 'Car & Motorbike' },
  { value: 'CDs & Vinyl', label: 'CDs & Vinyl' },
  { value: 'Computers & Accessories', label: 'Computers & Accessories' },
  { value: 'DVD & Blu-ray', label: 'DVD & Blu-ray' },
  { value: 'Electronics & Photo', label: 'Electronics & Photo' },
  { value: 'Garden & Outdoors', label: 'Garden & Outdoors' },
  { value: 'Health & Personal care', label: 'Health & Personal care' },
  { value: 'Home & Kitchen', label: 'Home & Kitchen' },
  { value: 'Industrial & Scientific', label: 'Industrial & Scientific' },
  { value: 'Large Appliances', label: 'Large Appliances' },
  { value: 'Luggage & Travel Gear', label: 'Luggage & Travel Gear' },
  { value: 'Musical Instruments', label: 'Musical Instruments' },
  { value: 'Video Games & Consoles', label: 'Video Games & Consoles' },
  { value: 'Pet Supplies', label: 'Pet Supplies' },
  { value: 'Sports & Outdoors', label: 'Sports & Outdoors' },
  { value: 'Stationary & Office Supplies', label: 'Stationary & Office Supplies' },
  { value: 'Toys & Games', label: 'Toys & Games' }
]