# Generated by Django 4.1.5 on 2023-04-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_about_product_dimensions_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
