# Generated by Django 4.1.5 on 2023-04-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_image_product_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_9',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
