# Generated by Django 4.1.5 on 2023-04-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_likers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likers',
        ),
    ]
